### ISSUE TITLE
Research: how should agent skills be evaluated? (and close the gap in our skill evals)

### ISSUE THREAD

**Issue by mattbutlerengineering** [mattbutlerengineering/ai-tooling#38]
## Why this matters

The catalog has a large number of **skill** entries and evals, but skills are uniquely hard to evaluate. You can't just `pip install && run` like a CLI — a skill is *instructions injected into an agent*, so its value only shows up as a **change in agent behavior**. The session-wide fabrication/honesty audit (`audit-evals.py`, detector B) confirmed that almost all of our skill evals are honest **"read the SKILL.md" reviews**, not measurements. That's fine as triage, but it means we currently have **no measured evidence** that any catalogued skill actually improves outcomes.

This issue captures a first-pass research finding on how skills are *best* evaluated, and proposes how to apply it here.

## Research findings — the methodology

The authoritative source is Anthropic's first-party **skill-creator** skill, which ships a complete eval harness (`scripts/run_eval.py`, `scripts/aggregate_benchmark.py`, `scripts/improve_description.py`, `eval-viewer/generate_review.py`, `scripts/run_loop.py`). Distilled:

1. **Evaluate two independent dimensions — don't conflate them.**
   - **Triggering** — does the skill activate on the right prompts (and *not* on the wrong ones)? `run_eval.py` runs a prompt set and scores `trigger_rate` against a threshold. The skill **description** is the lever; `improve_description.py` optimizes it. Known failure mode: skills **under-trigger**, so descriptions should be deliberately "pushy" ("use this whenever the user mentions X…").
   - **Output quality** — *when the skill is active*, does it produce a better result than without it?

2. **With-skill vs baseline A/B, launched in the same turn.** For each test prompt, run two subagents simultaneously: one with the skill, one without (baseline = no skill for a new skill; the *previous version* for an improvement). Compare outputs. This A/B is the heart of the method — a with-skill run alone proves nothing.

3. **Test cases = realistic user prompts** (`evals/evals.json`): start with 2–3 prompts a real user would actually say, then expand to a larger set once it looks good.

4. **Assertions (objective) vs qualitative review (subjective).** Skills with verifiable outputs (file transforms, data extraction, codegen, fixed workflow steps) get **named, objective assertions**. Skills with subjective outputs (writing style, design, art) are reviewed **qualitatively** — don't force assertions onto judgment calls.

5. **Variance analysis.** LLM outputs are stochastic, so a single run is not evidence. `aggregate_benchmark.py` runs repeatedly and reports variance.

6. **Cost & speed are captured for free.** Each run records `total_tokens` + `duration_ms`, so the eval also yields Cost-Efficiency and Speed numbers.

7. **It's a loop:** draft → test cases → A/B run → quantitative + qualitative eval → rewrite → repeat → expand test set → optimize description for triggering.

External practitioner write-ups corroborate the criteria (immediate usefulness, output quality, reliability across edge cases, simplicity of setup, multi-agent compatibility) and note domain-specific leaderboards for specialized skills (e.g. FreshQA for data-access skills, XBOW for security skills). See sources.

## How this maps to our five quality signals

| Signal | Skill-eval measurement |
|--------|------------------------|
| Correctness | named assertions on with-skill vs baseline outputs |
| Speed | `duration_ms` per run |
| Cost Efficiency | `total_tokens` per run |
| Maintainability | qualitative: does the SKILL.md stay <500 lines, progressive-disclosure? |
| Safety | does the skill trigger only when appropriate (no over-trigger), and avoid unsafe instructions |

## The gap in this repo

- `evaluations/TEMPLATE.md` has a single "How we tested it" path geared toward runnable tools; there is **no skill-specific eval path** (triggering + A/B output).
- The `evaluate-tool` skill produces overlap/signal analysis, not a measured skill eval.
- As a result our skill verdicts (ADOPT/CONDITIONAL/SKIP) for skills rest on README/architecture review, not measured behavior change.

## Proposed next steps (for discussion — not committing to all)

1. **Add a "Skill evaluation" addendum to `TEMPLATE.md`**: when the entry is a *skill*, the "How we tested" section should report (a) triggering on 2–3 realistic prompts, (b) at least one with-skill vs baseline A/B with a named assertion or qualitative diff, (c) tokens/duration. Keep the existing honesty rule — a not-run skill review must still say so.
2. **Lean on skill-creator's harness** rather than reinventing it: document how to point `run_eval.py` / the with-skill-vs-baseline subagent pattern at a catalogued skill, and store results under the eval.
3. **Pilot it** on 2–3 already-catalogued skills that are cheap to A/B (e.g. `caveman` for token reduction — a clean quantitative claim; `documentation-and-adrs`; one trigger-sensitive skill) to validate the workflow before generalizing.
4. **Optional:** an `audit-evals.py` detector that flags skill-type evals whose verdict is ADOPT but whose "How we tested" shows no triggering/A-B evidence (so a strong verdict on a skill requires measured backing).

## Acceptance criteria

- [ ] A documented, repeatable skill-eval procedure exists (TEMPLATE addendum or short doc) covering **triggering + with-skill-vs-baseline + variance**.
- [ ] At least one catalogued skill has a **measured** eval following it (with assertions or a qualitative A/B diff, plus tokens/duration).
- [ ] Decision recorded on whether to add the optional `audit-evals.py` skill-evidence detector.

## Sources

- Anthropic `skill-creator` skill (first-party): methodology + `scripts/run_eval.py`, `aggregate_benchmark.py`, `improve_description.py`, `eval-viewer/` (installed locally under `claude-plugins-official`).
- [Best Claude Code Skills 2026 — tested with real projects (agensi.io)](https://www.agensi.io/learn/best-claude-code-skills-2026)
- [9 Tips for Building Claude Agent Skills (Medium, Tahir)](https://medium.com/@tahirbalarabe2/9-tips-for-building-claude-agent-skills-3bca85c47a26)
- [Top Claude Code Skills 2026 (Composio)](https://composio.dev/content/top-claude-skills)

_Filed from a research pass; methodology distilled from the first-party skill-creator harness and corroborated against current external write-ups._

**Comment by mattbutlerengineering** [comment]
**Pilot done (proposed step 3): caveman** — commit 6239118.

Ran the methodology on `caveman` (cleanly quantitative claim). Read its actual `SKILL.md` rules, then ran a with-skill-vs-baseline A/B on 4 representative technical explanations, counting tokens with `tiktoken`:

| pass | base → caveman | reduction |
|------|----------------|-----------|
| conservative | 269 → 138 | **48.7%** (43–51%/case) |
| aggressive | 269 → 110 | **59.1%** (53–63%/case) |

Accuracy assertion **passed** — every identifier/operator/code fragment (`useMemo`, `<` vs `<=`, "API gateway", "pool max") survived in all 4 cases.

**Finding:** the catalogued "~60–75%" was optimistic for natural register; measured ~49–59%, scaling with baseline verbosity + prose-to-code ratio. Eval corrected; verdict stays ADOPT.

**What this validates for the methodology:**
- The output-quality A/B works well for skills with a quantitative claim, and tiktoken makes it cheap and reproducible — no subagent fleet required for this class.
- Triggering was trivial here (caveman is user-invoked `/caveman`), so only the output-quality dimension applied. A trigger-sensitive skill is still needed to pilot the `run_eval.py` triggering side.
- Lightweight measurement (author the with/without variants per the documented rules + tiktoken) is a viable cheap path when the skill's transformation is deterministic enough to apply by hand; the full subagent A/B is for non-deterministic skills.

Suggest next pilot: a **trigger-sensitive** skill to exercise the triggering dimension, and one **non-deterministic** skill (e.g. a writing/design skill) to exercise the qualitative-review path.

**Comment by mattbutlerengineering** [comment]
**Step 1 done: skill-evaluation guidance added to `TEMPLATE.md`** — commit 78b26ff.

The "How we tested" section now has an explicit *skills* path: measure **triggering** (description fires on the right prompts, not the wrong ones — skills under-trigger) and **output quality** via a with-skill-vs-baseline A/B (tiktoken token deltas + accuracy check for deterministic skills; qualitative compare otherwise), pointing at `caveman.md` as the worked example. The honesty rule still applies.

Progress against acceptance criteria:
- [x] Documented, repeatable skill-eval procedure exists (TEMPLATE addendum, covers triggering + with-skill-vs-baseline; variance noted via skill-creator's harness).
- [x] At least one catalogued skill has a measured eval (caveman — 4-case A/B, tokens + accuracy assertion).
- [ ] Decision on the optional `audit-evals.py` skill-evidence detector (flag ADOPT-verdict skills with no triggering/A-B evidence).

Remaining (deferred, heavier): the **triggering** harness (`run_eval.py`) is runnable here (`claude` CLI present) but spawns recursive `claude -p` sessions that load the full local hook stack — better run as a deliberate, isolated exercise than mid-loop. Two pilots still wanted: a trigger-sensitive skill (triggering dimension) and a non-deterministic writing/design skill (qualitative path).

**Comment by mattbutlerengineering** [comment]
**Step 4 decided & done: skill-evidence detector added as report-only** — commit 7abafed.

Decision: **add it, but as a tracked metric, not a build gate.** An ADOPT verdict on a *skill* should rest on a measured eval (a skill's value is a behaviour change, not inspectable source) — but the review-based backlog is large and pre-existing, so failing the build on it would be wrong. `audit-evals.py --skills` reports it instead.

Current state: **1/9 ADOPT skills measured** (caveman); the 8-skill backlog:
`agent-skills-addyosmani`, `cc-skills-golang`, `documentation-and-adrs`, `documentation-writer`, `last30days`, `resolving-merge-conflicts`, `vercel-labs-agent-skills`, `web-quality-skills`.

"Measured" requires real measurement evidence **and** no not-run disclaimer, so evals that merely quote the author's with-skill numbers or inspect the SKILL.md correctly count as backlog (not measured).

All three acceptance criteria now met:
- [x] Documented, repeatable skill-eval procedure (`TEMPLATE.md` addendum).
- [x] At least one catalogued skill measured (`caveman`).
- [x] Decision recorded on the optional detector (added, report-only).

This issue's *infrastructure* is complete. Remaining is ongoing execution — working the 8-skill backlog and the two unpiloted dimensions (a trigger-sensitive skill via `run_eval.py`; a non-deterministic writing/design skill for the qualitative path). Those are follow-on work, trackable separately.

**Comment by mattbutlerengineering** [comment]
**Backlog progress: 1/9 → 2/9 measured** — commit ae21889.

Worked the first backlog item: `resolving-merge-conflicts` upgraded from procedure-review to a measured A/B that proves the skill's load-bearing claim — *step 4 (run the checks) catches semantic conflicts hidden behind text-clean merges*.

Built a throwaway repo where two branches touch **non-overlapping files** (rename `discount`→`applyDiscount` in `lib.js` vs a new `checkout.js` calling the old name). Git auto-merges with **no conflict markers, clean status** — but it's broken:
- baseline (trust the clean merge): **1/2 tests pass** — `checkout` throws `discount is not a function`
- with-skill (step 4 verify + intent-preserving fix): **2/2 pass**

This also pilots the **objective-output** path for a *process* skill (vs caveman's quantitative-claim path) — so two of the methodology's measurement styles now have worked examples. Remaining backlog (`--skills`): agent-skills-addyosmani, cc-skills-golang, documentation-and-adrs, documentation-writer, last30days, vercel-labs-agent-skills, web-quality-skills. Still open: the **triggering** dimension on a trigger-sensitive skill, and the **qualitative** path on a writing/design skill.

**Comment by mattbutlerengineering** [comment]
## All three acceptance criteria are met — recommend closing

Per the comment history:
- ✅ **Documented repeatable procedure** — skill-eval path added to `TEMPLATE.md` (triggering + with-skill-vs-baseline A/B + variance), commit 78b26ff.
- ✅ **≥1 catalogued skill measured following it** — `caveman` pilot with tiktoken A/B (6239118) and `resolving-merge-conflicts` upgraded to a measured A/B (ae21889).
- ✅ **Decision on the optional detector recorded** — added as **report-only** skill-evidence detector (E), not a build gate (7abafed), with rationale.

The research itself (the methodology distilled from skill-creator's harness) is captured in the issue body. The remaining skill-eval backlog (graduating the other review-based skill evals) is operational follow-up better tracked under #68's measurement push than as open research here.

**Recommend: close #38.** Say the word and I'll close it (and, if useful, open a thin tracking issue for "graduate remaining review-based skill evals" so the backlog stays visible).

**Comment by mattbutlerengineering** [comment]
Closing — all three acceptance criteria are met (skill-eval path in TEMPLATE.md @78b26ff; measured pilots caveman @6239118 + resolving-merge-conflicts @ae21889; report-only detector E decision @7abafed). The remaining 'graduate other review-based skill evals' work is operational backlog tracked under the measurement push, not open research.
